import json
import os
import re
import textstat


# Function to calculate the Gunning Fog Index using the textstat library
def gunningFog_textstat(text):
    score = textstat.gunning_fog(text)
    return score


# Main function to process the input file, calculate readability scores, and save results
def main(file, dirname):
    with open(file, "r", encoding="utf8") as rf:
        lines = []
        for i, line in enumerate(rf.readlines()):
            line = json.loads(line)

            # Continue only if queryID is in email_indices
            if i not in [2, 3, 10, 13, 27]:  # Indices of results generated by prompts associated to emails
                lines.append(line)
                continue
            message = line["message"]

            # Check if the response contains typical email keywords
            if len(re.findall("Dear", message)) == 0 and len(re.findall("Hello", message)) == 0 \
                    and len(re.findall("Hi", message)) == 0 and len(re.findall("Hey", message)) == 0 \
                    and len(re.findall("click", message.lower())) == 0:
                line["gunningfog_email"] = None
            else:
                # Extract the main content of the email
                if re.search("Subject:", message):
                    src_content = "Subject:" + message.split("Subject:")[-1]
                    src_content = src_content.split("---")[0].strip()
                elif re.search("Dear", message):
                    src_content = "Dear" + message.split("Dear")[-1]
                    src_content = src_content.split("---")[0].strip()
                else:
                    src_content = message.split("---")[0].strip()
                # Start measuring fog
                line["gunningfog_email"] = gunningFog_textstat(src_content)
            lines.append(line)

    # Write the results to the output file
    outfile = os.path.join(dirname, "fogemail_" + os.path.basename(file))
    with open(outfile, "w", encoding="utf8") as wf:
        for line in lines:
            wf.write(json.dumps(line) + "\n")


if __name__ == '__main__':
    input_filename = "/home/malicious-gpt/malicious_LLM_responses/service/QA-XXXGPT-1.json"
    dirname = "../mailFluency/"
    if not os.path.exists(dirname):
        os.mkdir(dirname)
    main(input_filename, dirname)
